language: scala

jdk:
  - oraclejdk8

env:
  global:
    - IDEA_SDK=$HOME/.ScalaPluginIC/sdk

before_script:
  - sbt packagePlugin test:compile

script:
  - sbt test

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $IDEA_SDK

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $IDEA_SDK -name "ideaIC-*.zip" -delete
  # remove all but the newest ideaSDK
  - ls -Art $IDEA_SDK | tail -n 1 | xargs find $IDEA_SDK -maxdepth 1 -mindepth 1 -not -name | xargs rm -r
